    apiVersion: agent.open-cluster-management.io/v1
    kind: KlusterletAddonConfig
    metadata:
      name: local-cluster
    spec:
      certPolicyController:
        enabled: true
      policyController:
        enabled: true
