apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:grc:clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:grc:clusterrole
subjects:
- kind: ServiceAccount
  name: grc-sa
  namespace: multicluster-engine
  