apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grc-grc-policy-addon-rolebinding
  namespace: multicluster-engine
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grc-grc-policy-addon-role
subjects:
- kind: ServiceAccount
  name: grc-policy-addon-sa
