apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grc-grc-rolebinding
  namespace: multicluster-engine
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grc-grc-role
subjects:
- kind: ServiceAccount
  name: grc-sa
