apiVersion: apps/v1
kind: Deployment
metadata:
  name: grc-policy-addon-controller
  namespace: multicluster-engine
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grc
      component: ocm-policy-addon-ctrl
      release: grc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      creationTimestamp: null
      labels:
        app: grc
        app.kubernetes.io/instance: grc
        app.kubernetes.io/name: grc
        chart: grc-chart-2.11.0
        component: ocm-policy-addon-ctrl
        name: governance-policy-addon-controller
        ocm-antiaffinity-selector: grcpolicyaddon
        release: grc
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
                - arm64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - grcpolicyaddon
              topologyKey: topology.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - grcpolicyaddon
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - args:
        - controller
        command:
        - governance-policy-addon-controller
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: CERT_POLICY_CONTROLLER_IMAGE
          value: quay.io/stolostron/cert-policy-controller@sha256:6020e552c5f302e7d29ff8416938140865bc76f330d386bfed41140f79dbf6c8
        - name: CONFIG_POLICY_CONTROLLER_IMAGE
          value: quay.io/stolostron/config-policy-controller@sha256:50eb96f4aea9ac957429dfa7997f11b5abbb44324f755036f5fc449f40732dbf
        - name: KUBE_RBAC_PROXY_IMAGE
          value: quay.io/stolostron/kube-rbac-proxy@sha256:9626cb9b2ee8f00d2abdb14cd2ce56d77435859071c10d8394bc7ee2754ce87f
        - name: GOVERNANCE_POLICY_FRAMEWORK_ADDON_IMAGE
          value: quay.io/stolostron/governance-policy-framework-addon@sha256:343e34ce7b7ff557211f11b6eccc246013b757daf25074160a1931bdbc7724a9
        image: quay.io/stolostron/governance-policy-addon-controller@sha256:e9b34974e8b5f1258f491675b11adfaab05b6c0479a73d84fd42e278817a5836
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: open-cluster-management-image-pull-credentials
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: grc-policy-addon-sa
      serviceAccountName: grc-policy-addon-sa
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      volumes:
      - emptyDir: {}
        name: tmp
